name: crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs).
version: 4.0.2
homepage: https://github.com/cachapa/crdt
repository: https://github.com/cachapa/crdt
issue_tracker: https://github.com/cachapa/crdt/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  build_runner: ^2.1.1
  moor: ^4.4.1
  moor_generator: ^4.4.1
  path: ^1.8.0
  sqlite3: ^1.1.2
  # no dependencies, no problems

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
